In [1]:
import pandas as pd
df = pd.read_excel("Dataset for Data Analytics.xlsx")

In [2]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [4]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [5]:
df["Sales"] = df["Quantity"] * df["UnitPrice"]

In [6]:
df["OrderYear"] = pd.to_datetime(df["Date"]).dt.year

In [7]:
df["OrderMonth"] = pd.to_datetime(df["Date"]).dt.month

In [8]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Sales,OrderYear,OrderMonth
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2853.10,2023,1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,302.70,2024,8
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40,2024,2
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,273.19,2023,10
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2504.04,2025,5

In [9]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Sales"] < lower) | (df["Sales"] > upper)]

print("Number of outliers:", len(outliers))

Number of outliers: 8

In [10]:
df = df[(df["Sales"] >= lower) & (df["Sales"] <= upper)]

In [11]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
Sales              0
OrderYear          0
OrderMonth         0
dtype: int64

In [12]:
df.to_csv("cleaned_dataset.csv", index=False)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1192 entries, 0 to 1199
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1192 non-null   object
 1   Date             1192 non-null   datetime64[ns]
 2   CustomerID       1192 non-null   object
 3   Product          1192 non-null   object
 4   Quantity         1192 non-null   int64
 5   UnitPrice        1192 non-null   float64
 6   ShippingAddress  1192 non-null   object
 7   PaymentMethod    1192 non-null   object
 8   OrderStatus      1192 non-null   object
 9   TrackingNumber   1192 non-null   object
 10  ItemsInCart      1192 non-null   int64
 11  CouponCode       1192 non-null   object
 12  ReferralSource   1192 non-null   object
 13  TotalPrice       1192 non-null   float64
 14  Sales            1192 non-null   float64
 15  OrderYear        1192 non-null   int32
 16  OrderMonth       1192 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(9)
memory usage: 158.3+ KB